[package]
name = "rsnano_nullable_http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_output_tracker = { path = "../output_tracker" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
reqwest = { version = "0", default-features = false, features = ["json"] }
tokio = { version = "1", features = [
    "macros",
] }
tokio-util = "0"

[dev-dependencies]
axum = "0"
