[package]
name = "signature-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../../core" }
rsnano_ledger = { path = "../../ledger" }
rsnano_store_lmdb = { path = "../../store_lmdb" }
ed25519-dalek-blake2b = "1.0.2"
