[package]
name = "rsnano_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../core" }
rsnano_node = { path = "../node" }
rsnano_rpc_server = { path = "../rpc_server" }
anyhow = "1"
tokio = { version = "1", features = ["signal"] }
