[package]
name = "rsnano_websocket_messages"
version = "0.1.0"
edition = "2021"

[dependencies]
rsnano_core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
num-derive = "0"
num-traits = "0"

