name: Static Analyzers

on: [ push, pull_request ]

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: scripts/ci/cargo-fmt-check.sh
