name: Unit Tests

on: [push, pull_request]
env:
  RUST_BACKTRACE: '1'

jobs:
  macos_test:
    name: macOS
    strategy:
      fail-fast: false
    runs-on: macos-14
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: scripts/ci/prepare/macos/prepare.sh

      - name: Build Tests
        id: build
        run: cargo build --all-targets

      - name: Run Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: cargo test -q

  linux_test:
    name: Linux
    timeout-minutes: 30
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Prepare
        run: sudo -E scripts/ci/prepare/linux/prepare.sh

      - name: Build Tests
        id: build
        run: cargo build --all-targets

      - name: Run Tests
        if: steps.build.outcome == 'success' && (success() || failure())
        run: cargo test -q
